### ISSUE TITLE
关于加载预训练参数

### ISSUE THREAD

**Issue by q2479036243** [laisimiao/ViPT_HOT2023#2]
请问在HOT上的微调是加载的哪个预训练权重文件呢？

**Comment by laisimiao** [comment]
ostrack

**Comment by q2479036243** [comment]
> ostrack

感谢您的回复，我通过ViPT中的连接下载了OSTrack的预训练权重，之后在yaml配置文件中修改NODEL.PRETRAIN_FILE路径。但是在训练过程中发现，模型权重没有被加载，会报告`Load pretrained model missing_keys: ['backbone.patch_embed_prompt_vis.proj.weight', 'backbone.patch_embed_prompt_vis.proj.bias',...]`。如果加载的是训练好的ViPT_all.pth.tar则不会出现该情况，请问是哪里需要修改吗？

**Comment by laisimiao** [comment]
训练代码没有放，你直接用不行

**Comment by q2479036243** [comment]
> 训练代码没有放，你直接用不行

lib/train中的代码不是训练代码吗？如果您方便的话，能提供训练部分吗？

**Comment by laisimiao** [comment]
训练部分可以根据我的youtube讲解视频进行自己复现

**Comment by q2479036243** [comment]
> 训练部分可以根据我的youtube讲解视频进行自己复现

好的，感谢
